"""English idiom / euphemism of the day with Russian translation and usage example.

Educational language content for the digest (users Маша and Максим). Generated by
gpt-5.4-mini — there is no reliable free "idiom of the day" API, and this is language
learning content, not factual news, so model generation is appropriate here.

Per project rules: NO HARDCODED FALLBACKS — if generation fails, return None and the
scheduler simply omits the section.
"""

import json
import logging
import random
from datetime import datetime
from typing import Optional, Dict, Any

from src.utils.openai_client import get_client

logger = logging.getLogger(__name__)

# Rotate the kind of phrase day to day so the section stays varied.
_PHRASE_KINDS = [
    "распространённая английская идиома",
    "менее очевидная, но употребимая английская идиома",
    "английский эвфемизм (мягкая/деликатная формулировка)",
    "разговорное английское выражение (phrasal idiom)",
]


async def get_idiom_of_day() -> Optional[Dict[str, Any]]:
    """Generate an English idiom/euphemism of the day.

    Returns:
        {
            "phrase": str,          # English idiom/euphemism
            "kind": str,            # "идиома" | "эвфемизм" | ...
            "meaning_ru": str,      # Russian translation / meaning
            "example_en": str,      # usage example in English
            "example_ru": str,      # translation of the example
        }
        or None if generation fails.
    """
    try:
        # Seed the request with the date so reruns on the same day are stable-ish
        # but different days get different phrases.
        today = datetime.now().strftime("%Y-%m-%d")
        kind = random.choice(_PHRASE_KINDS)

        prompt = f"""Подбери ОДНУ интересную английскую идиому или эвфемизм на сегодня ({today}).
Тип на сегодня: {kind}.

Требования:
- Выражение должно быть реальным и употребимым носителями (никаких выдуманных).
- Желательно не самое заезженное (избегай "break a leg", "piece of cake", если можно).
- Дай точный перевод/смысл на русском.
- Приведи естественный пример употребления на английском и его перевод на русский.

Верни СТРОГО JSON-объект без markdown и пояснений:
{{
  "phrase": "английское выражение",
  "kind": "идиома" или "эвфемизм",
  "meaning_ru": "перевод/смысл на русском",
  "example_en": "пример на английском",
  "example_ru": "перевод примера на русский"
}}"""

        response = await get_client().chat.completions.create(
            model="gpt-5.4-mini",
            max_completion_tokens=300,
            temperature=1.0,
            messages=[
                {
                    "role": "system",
                    "content": "You are an English teacher for Russian speakers. Reply with valid JSON only.",
                },
                {"role": "user", "content": prompt},
            ],
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if present
        if "```json" in raw:
            raw = raw.split("```json")[1].split("```")[0].strip()
        elif "```" in raw:
            raw = raw.split("```")[1].split("```")[0].strip()

        data = json.loads(raw)

        phrase = (data.get("phrase") or "").strip()
        meaning = (data.get("meaning_ru") or "").strip()
        if not phrase or not meaning:
            logger.warning("Idiom of day: missing phrase or meaning, skipping")
            return None

        result = {
            "phrase": phrase,
            "kind": (data.get("kind") or "идиома").strip(),
            "meaning_ru": meaning,
            "example_en": (data.get("example_en") or "").strip(),
            "example_ru": (data.get("example_ru") or "").strip(),
        }
        logger.info(f"✓ Idiom of day: {phrase} — {meaning[:40]}")
        return result

    except Exception as e:
        logger.warning(f"Failed to get idiom of day: {type(e).__name__}: {e}")
        return None
