"""Place of the day: cafe, restaurant, park or interesting location to visit.

Recommendation content for the digest — one place per day. Tbilisi for Маша and
Максим (a place to visit together), Vienna for Юля. Generated by gpt-5.4-mini:
there is no reliable free "places to visit" API, and this is a recommendation of
real well-known places, not factual news, so model generation is appropriate here
(same reasoning as idiom_of_day.py).

History: shown places are persisted per city to data/place_history*.json for 28
days and passed to the model as an exclusion list, so a place is never repeated
within a 28-day window. Entries older than 28 days are dropped on each run. The
chosen place is cached per day, so all recipients of a city get the same place
on a given date.

Per project rules: NO HARDCODED FALLBACKS — if generation fails, return None and
the scheduler simply omits the section.
"""

import json
import logging
import os
import random
from datetime import datetime, timedelta
from typing import Optional, Dict, Any, List

from src.utils.openai_client import get_client

logger = logging.getLogger(__name__)

# Places shown within this window are excluded and never repeated.
_HISTORY_DAYS = 28
_DATA_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "data",
)

def _history_path(city: str) -> str:
    """History file per city (Tbilisi keeps the original filename)."""
    fname = "place_history.json" if city == "tbilisi" else f"place_history_{city}.json"
    return os.path.join(_DATA_DIR, fname)


# Rotate the kind of place day to day so the section stays varied.
_PLACE_KINDS = {
    "tbilisi": [
        "хипстерское кафе или спешелти-кофейня (specialty coffee, локальные обжарщики)",
        "небанальный ресторан или бистро (новая грузинская кухня, авторские места, натуральное вино)",
        "винный бар, крафтовый бар или другое вечернее место с характером",
        "неочевидная локация (дворик, арт-пространство, необычный район, блошиный рынок, скрытая смотровая)",
    ],
    "vienna": [
        "атмосферное кафе или кофейня (в том числе классические венские кофейни)",
        "хороший ресторан (австрийская или интересная кухня)",
        "парк, сад или зелёная зона для прогулки",
        "интересная локация (смотровая площадка, необычный район, музей, арт-пространство, рынок)",
    ],
}

# Per-city wording for the generation prompt.
_CITY_META = {
    "tbilisi": {
        "city_prep": "Тбилиси",          # "место в ..."
        "audience": "паре (Максим и Мария)",
        "guide": "You are a local Tbilisi guide for Russian speakers. Recommend only real, existing places. Reply with valid JSON only.",
        # Анти-попса: не туристический мейнстрим, а места «для местных».
        "style": (
            "\n- НЕ предлагай попсовые туристические места (Мтацминда, фуникулёр, мост Мира, "
            "серные бани, пр. Руставели «в лоб», Fabrika и другой очевидный мейнстрим).\n"
            "- Выбирай места, куда ходят местные и экспаты: хипстерские, камерные, неочевидные — "
            "но реально существующие и работающие."
        ),
    },
    "vienna": {
        "city_prep": "Вене",
        "audience": "девушке (Юля)",
        "guide": "You are a local Vienna guide for Russian speakers. Recommend only real, existing places. Reply with valid JSON only.",
        "style": "",
    },
}


def _load_history(city: str) -> List[Dict[str, Any]]:
    """Load the place history list (oldest → newest). Returns [] on any error."""
    try:
        with open(_history_path(city), "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            return data
    except FileNotFoundError:
        pass
    except Exception as e:
        logger.warning(f"Could not read place history: {type(e).__name__}: {e}")
    return []


def _trim_history(history: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Keep only entries from the last _HISTORY_DAYS days."""
    cutoff = (datetime.now() - timedelta(days=_HISTORY_DAYS)).strftime("%Y-%m-%d")
    return [h for h in history if h.get("date", "") >= cutoff]


def _save_history(city: str, history: List[Dict[str, Any]]) -> None:
    """Persist the place history (trimmed to the last _HISTORY_DAYS days)."""
    try:
        os.makedirs(_DATA_DIR, exist_ok=True)
        with open(_history_path(city), "w", encoding="utf-8") as f:
            json.dump(_trim_history(history), f, ensure_ascii=False, indent=2)
    except Exception as e:
        logger.warning(f"Could not write place history: {type(e).__name__}: {e}")


async def get_place_of_day(city: str = "tbilisi") -> Optional[Dict[str, Any]]:
    """Recommend one place in the city to visit, avoiding repeats within 28 days.

    Args:
        city: "tbilisi" or "vienna".

    Returns:
        {
            "name": str,        # place name
            "kind": str,        # "кафе" | "ресторан" | "парк" | "локация"
            "area": str,        # district / area of the city
            "description": str, # why it is worth visiting (Russian, 1-2 sentences)
        }
        or None if generation fails.
    """
    if city not in _CITY_META:
        city = "tbilisi"
    meta = _CITY_META[city]

    today = datetime.now().strftime("%Y-%m-%d")
    history = _trim_history(_load_history(city))

    # Same day → return the already-chosen place so every recipient sees the same one.
    if history and history[-1].get("date") == today:
        cached = {k: v for k, v in history[-1].items() if k != "date"}
        logger.info(f"Place of day [{city}] (cached for {today}): {cached.get('name')}")
        return cached

    recent_places = [h.get("name", "") for h in history if h.get("name")]

    try:
        kind = random.choice(_PLACE_KINDS[city])

        avoid_block = ""
        if recent_places:
            joined = "\n".join(f"- {p}" for p in recent_places)
            avoid_block = (
                "\n\nНЕ предлагай эти места (они уже были за последние 28 дней):\n"
                + joined
            )

        prompt = f"""Порекомендуй ОДНО место в {meta['city_prep']}, которое стоит посетить {meta['audience']} на сегодня ({today}).
Тип на сегодня: {kind}.

Требования:
- Место должно быть РЕАЛЬНЫМ и существующим в {meta['city_prep']} (никаких выдуманных названий).
- Работающее место, которое можно найти на картах.
- Укажи район/местоположение.
- Дай короткое (1-2 предложения) живое описание на русском: чем место интересно и почему стоит сходить.{meta['style']}{avoid_block}

Верни СТРОГО JSON-объект без markdown и пояснений:
{{
  "name": "название места",
  "kind": "кафе" или "ресторан" или "парк" или "локация",
  "area": "район/местоположение в {meta['city_prep']}",
  "description": "описание на русском, 1-2 предложения"
}}"""

        response = await get_client().chat.completions.create(
            model="gpt-5.4-mini",
            max_completion_tokens=300,
            temperature=1.0,
            messages=[
                {"role": "system", "content": meta["guide"]},
                {"role": "user", "content": prompt},
            ],
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if present
        if "```json" in raw:
            raw = raw.split("```json")[1].split("```")[0].strip()
        elif "```" in raw:
            raw = raw.split("```")[1].split("```")[0].strip()

        data = json.loads(raw)

        name = (data.get("name") or "").strip()
        description = (data.get("description") or "").strip()
        if not name or not description:
            logger.warning(f"Place of day [{city}]: missing name or description, skipping")
            return None

        result = {
            "name": name,
            "kind": (data.get("kind") or "локация").strip(),
            "area": (data.get("area") or "").strip(),
            "description": description,
        }

        # Record in history (keyed by date) so it is not repeated for 28 days.
        history.append({"date": today, **result})
        _save_history(city, history)

        logger.info(f"✓ Place of day [{city}]: {name} ({result['area']})")
        return result

    except Exception as e:
        logger.warning(f"Failed to get place of day [{city}]: {type(e).__name__}: {e}")
        return None
