name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-notification-bot:
    name: Build Notification Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/notification-bot:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/notification-bot:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/notification-bot:cache,mode=max

  redeploy:
    name: Redeploy
    runs-on: ubuntu-latest
    needs: [build-notification-bot]
    steps:
      - name: Restarting docker container
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_ADMIN_USER }}
          password: ${{ secrets.SERVER_ADMIN_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          envs: DOCKER_ACCESS_TOKEN,DOCKER_HUB_USERNAME
          script: |
            echo "$DOCKER_ACCESS_TOKEN" | sudo docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            cd /opt
            sudo sh redeploy-notification-bot.sh
